# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('solved', models.BooleanField(default=False)),
                ('solved_date', models.DateTimeField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f')),
                ('solved_by', models.CharField(blank=True, max_length=255)),
                ('response_text', models.TextField(blank=True)),
            ],
        ),
    ]
