# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20160611_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Issue',
        ),
    ]
