# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20160613_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='solved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_solved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
